---
- name: Create a directory on dev1 and dev2
  hosts: all
  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /path/to/your/directory
        state: directory
        mode: '0755'
