name: Pull Request Label Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  print-deps-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get and process pull request labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const depsLabels = labels
              .filter(label => label.startsWith('deps/'))
              .map(label => label.replace('deps/', ''));
            return depsLabels;

      - name: Print processed deps labels
        run: |
          echo "Processed Labels: ${{ steps.get-labels.outputs.result }}"
