name: Pull Request Label Workflow

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  print-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print label
        run: echo "The label is ${{ github.event.label.name }}"
