name: Pull Request Label Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  print-deps-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get and process pull request labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const depsLabels = labels
              .filter(label => label.startsWith('deps/'))
              .map(label => `--app-branch=fintechsys/${label.replace('deps/', '')}`);
            core.setOutput("depsLabels", depsLabels.join('  '));

      - name: Print processed deps labels
        run: |
          # echo "Processed Labels: ${{ steps.get-labels.outputs.depsLabels }}"
          export LABLES=$(echo "${{ steps.get-labels.outputs.depsLabels }}")
          echo "LABLES=${LABLES}" >> $GITHUB_ENV


      - name: Comment on PR
        uses: actions/github-script@v5
        with:
            github-token: ${{ secrets.ORG_TOKEN }}
            script: |
              const issue_number = context.issue.number;
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const message = "Site_Name: http://84.247.128.47:${{ env.PORTS }} \n\n \
              Username: ${{ steps.get-labels.outputs.depsLabels }} \n\n \
              PASSWORD: ${{ secrets.mariadb_pass }}";
              github.rest.issues.createComment({
                issue_number: issue_number,
                owner: owner,
                repo: repo,
                body: message
           
